### ISSUE TITLE
Vite compression compatibility & Subdist

### ISSUE THREAD

**Issue by chemeng** [sportsrecruits/vite-plugin-s3#2]
Hello, thanks for the plugin. I have 2 questions:

1) Is there a way to force the plugin to run after the compression plugin finishes (https://github.com/vbenjs/vite-plugin-compression)? Now it only uploads the non-compressed files and skips the compressed ones because it runs before them.
2) Is there a way to select which directory to upload instead of the c.build.outDir that does by default?

**Comment by jamesburrow23** [comment]
@chemeng Both of those options could be added to allow greater flexibility.  We could leverage something like the `enforce` option for Vite plugins that would ensure it's run after the compression plugin.   We could also add an option to the config you pass when registering the plugin for which path to use for retrieving assets.

I can experiment with this today and let you know or if you'd like to submit a PR I can review.  This plugin was created for our internal use and still has many features / tests we plan on adding but there's no timeline for what that looks like.

Thanks for your ideas!

**Comment by jamesburrow23** [comment]
@chemeng you can now customize the enforce behavior and the `uploadDir` with the latest release of this package.  The readme has been updated with the latest options.

https://www.npmjs.com/package/vite-plugin-s3

**Comment by chemeng** [comment]
Awesome, thanks guys
