### ISSUE TITLE
Possibility to use cloudfront

### ISSUE THREAD

**Issue by bjensen** [sportsrecruits/vite-plugin-s3#3]
Does the plugin support invaliding a Cloudfront distribution by providing a cloud front id and possibly a matcher?

**Comment by jamesburrow23** [comment]
Hi @bjensen,

We don't natively support invalidating a Cloudflare distribution in this package but it's possible you could achieve that by using the `onFinished` callback which is invoked after the plugin has finished uploading the built assets.
